import Img1 from './Images/1.jpg';
import Img2 from './Images/2.jpg';
import Img3 from './Images/3.jpg';
import Img4 from './Images/4.jpg';
import Img5 from './Images/5.jpg';
import Img6 from './Images/6.jpg';
import Img7 from './Images/7.jpg';
import Img8 from './Images/8.jpg';
import Img9 from './Images/9.jpg';
import Img10 from './Images/10.jpg';
import Img11 from './Images/11.jpg';
import Img12 from './Images/12.jpg';
import Img13 from './Images/13.jpg';
import Img14 from './Images/14.jpg';
import Img15 from './Images/15.jpg';
import Img16 from './Images/16.jpg';

const DummyGroups = [
  {
    _id: '1',
    name: 'Echidna',
    bio: 'Group of feet-lovers',
    pic: Img1,
    members: ['Shivam', 'Vishal', 'Kunj', 'Barbox', 'Zeemon'],
    rooms: [
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
      'general',
      'memes',
      'videos',
      'cp',
    ],
  },
  {
    _id: '2',
    name: 'VAC',
    bio: 'Gathering place of Otakus of Vadodara',
    pic: Img2,
    members: ['Shivam', 'Vishal', 'Kunj'],
    rooms: ['general', 'memes', 'videos', 'meetups'],
  },
  {
    _id: '3',
    name: 'Dharavi',
    bio: 'Dharavi ki pobilk',
    pic: Img3,
    members: ['Shivam', 'Vishal', 'Kunj', 'Barbox'],
    rooms: ['general', 'memes', 'videos', 'cat videos'],
  },
  {
    _id: '4',
    name: 'Degen',
    bio: 'Group of degens',
    pic: Img4,
    members: [
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
    ],
    rooms: ['general', 'memes', 'videos', 'simping'],
  },
  {
    _id: '5',
    name: 'E-fam',
    bio: 'Family cosplay',
    pic: Img5,
    members: [
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
    ],
    rooms: ['general', 'memes', 'videos', 'cosplay'],
  },
  {
    _id: '6',
    name: 'Strangers',
    bio: 'Cringe GC',
    pic: Img6,
    members: ['Shivam', 'Vishal'],
    rooms: ['general', 'memes', 'videos', 'collage'],
  },
  {
    _id: '7',
    name: 'Cum 24/7',
    bio: 'Daily Group Masturbation',
    pic: Img7,
    members: ['Shivam'],
    rooms: ['general', 'memes', 'videos', 'cum'],
  },
  {
    _id: '8',
    name: 'Echidna',
    bio: 'Group of feet-lovers',
    pic: Img8,
    members: ['Shivam', 'Vishal', 'Kunj', 'Barbox', 'Zeemon'],
    rooms: ['general', 'memes', 'videos', 'cp'],
  },
  {
    _id: '9',
    name: 'VAC',
    bio: 'Gathering place of Otakus of Vadodara',
    pic: Img9,
    members: ['Shivam', 'Vishal', 'Kunj'],
    rooms: ['general', 'memes', 'videos', 'meetups'],
  },
  {
    _id: '10',
    name: 'Dharavi',
    bio: 'Dharavi ki pobilk',
    pic: Img10,
    members: ['Shivam', 'Vishal', 'Kunj', 'Barbox'],
    rooms: ['general', 'memes', 'videos', 'cat videos'],
  },
  {
    _id: '11',
    name: 'Degen',
    bio: 'Group of degens',
    pic: Img11,
    members: [
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
    ],
    rooms: ['general', 'memes', 'videos', 'simping'],
  },
  {
    _id: '12',
    name: 'E-fam',
    bio: 'Family cosplay',
    pic: Img12,
    members: [
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
      'Shivam',
      'Vishal',
      'Kunj',
      'Barbox',
      'Zeemon',
    ],
    rooms: ['general', 'memes', 'videos', 'cosplay'],
  },
  {
    _id: '13',
    name: 'Strangers',
    bio: 'Cringe GC',
    pic: Img13,
    members: ['Shivam', 'Vishal'],
    rooms: ['general', 'memes', 'videos', 'collage'],
  },
  {
    _id: '14',
    name: 'Cum 24/7',
    bio: 'Daily Group Masturbation',
    pic: Img14,
    members: ['Shivam'],
    rooms: ['general', 'memes', 'videos', 'cum'],
  },
  {
    _id: '15',
    name: 'Strangers',
    bio: 'Cringe GC',
    pic: Img15,
    members: ['Shivam', 'Vishal'],
    rooms: ['general', 'memes', 'videos', 'collage'],
  },
  {
    _id: '16',
    name: 'Cum 24/7',
    bio: 'Daily Group Masturbation',
    pic: Img16,
    members: ['Shivam'],
    rooms: ['general', 'memes', 'videos', 'cum'],
  },
];

export default DummyGroups;
